version: "3.9"

services:
  srt-server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: srt-server
    restart: always
    ports:
      - 8181:8181/udp
      - 8080:8080
    networks:
      - srt

networks:
  srt:
    driver: bridge
