version: "3.7"

services:
  srt-server:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    container_name: srt-server
    restart: unless-stopped
    ports:
      - 8080:8080/udp
      - 8000:80
    networks:
      - srt

  express:
    build:
      context: ./express
      dockerfile: Dockerfile

    container_name: express
    restart: unless-stopped
    environment:
      - SEGMENTER_KMP_API=srt-server:8001
      - WEBAPP_API=https://piquetdestream.fly.io
    networks:
      - srt

networks:
  srt:
    driver: bridge
