version: "3.9"

services:
  srt-server:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    container_name: srt-server
    restart: always
    ports:
      - 8080:8080/udp
      - 8081:8081
      - 8082:8082/udp
      - 8000:80
    networks:
      - srt
  php:
    image: php:fpm-alpine
    networks:
      - srt
    volumes:
      - ./nginx/controller.php:/opt/media-framework/conf/controller.php

networks:
  srt:
    driver: bridge
